ошибки через try catch


include exeption
throw 
try
catch

some_f

functional
